yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:pk>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:pk>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField("title", max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='ТЕКСТ ПОСТА',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='ДАТА',
                                    help_text='help_date'
                                    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='АВТОР',
        help_text='help_user'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='ГРУППА',
        help_text='Выберите группу'
    )

    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(verbose_name='ТЕКСТ комментария',
                            help_text='Введите текст')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='ДАТА',)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'group': forms.Select(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {'group': "Группы"}

        def clean_subject(self):
            data = self.cleaned_data['text']
            if data == '':
                raise forms.ValidationError('Отсутствует какой-либо текст')
            return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'author': forms.Textarea(attrs={'class': 'form-control'}),
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Comment, Follow
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

NUMBER_OF_POSTS = 10


@cache_page(20)
def index(request):
    template = 'posts/index.html'
    posts = (Post.objects.all())
    paginator = Paginator(posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group.objects.prefetch_related('posts'),
                              slug=slug
                              )
    template = 'posts/group_list.html'
    posts_all = group.posts.all()
    paginator = Paginator(posts_all, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    author = get_object_or_404(User, username=username)
    posts = user.posts.all()
    paginator = Paginator(posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if (request.user.is_authenticated and Follow.objects.filter(
            user=request.user, author=author).exists()):
        following = True
    context = {
        'author': author,
        #'user': user,
        'posts': posts,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post_count = Post.objects.filter(author=post.author).count()
    comments = Comment.objects.filter(post=post)
    form_comments = CommentForm(request.POST or None)
    context = {
        'post': post,
        'post_count': post_count,
        'comments': comments,
        'form_comments': form_comments,

    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if form.is_valid():
        new_form = form.save(commit=False)
        new_form.author = request.user
        new_form.save()
        return redirect(f'/profile/{request.user}/')
    form = PostForm()
    context = {
        'is_edit': False,
        'form': form,
    }

    return render(request, 'posts/create.html', context)


@login_required
def post_edit(request, pk):
    is_edit = True,
    post = get_object_or_404(Post, pk=pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if post.author != request.user:
        return redirect(f'/posts/{pk}/')

    if form.is_valid():
        form.save()
        return redirect(f'/posts/{pk}/')

    context = {
        'pk': pk,
        'is_edit': is_edit,
        'form': form,

    }

    return render(request, 'posts/create.html', context)


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', pk=pk)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create.html
 {% extends 'base.html' %}
 {% block title %} Новая запись {{ user.username }} {% endblock %}
 {% load thumbnail %}
 {% block content %}
     <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                  {% if is_edit %}Редактировать пост
                  {% else %}Новый пост{% endif %}
              </div>
              <div class="card-body">
                  {% if is_edit %}
                  <form method="post" action="{% url 'posts:post_edit' pk %}" enctype="multipart/form-data" >
                      {% else %}
                  <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data" >
                  {% endif %}
               {% csrf_token %}
               <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger" >*</span>
                    </label>
                    {{ form.text }}
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                    {{ form.group.label_tag }}
                    </label>
                      {{ form.group }}

                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                      <label for="id_image">
                      Картинка
                    </label>
                        {{ form.image }}
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}Сохранить{% else %}
                            Добавить{% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
 {% endblock %}

yatube/templates/posts/follow.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}  {% endblock %}
{% block content %}
{% include 'includes/switcher.html' %}
  <body>

      <h1>Любимые авторы</h1>
    <main>
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                 <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
             {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
             {% endthumbnail %}
            <p>{{ post.text }}</p>
            <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a></p>
             <style>
               .btn {
                display: inline-block; /* Строчно-блочный элемент */
                background-color: lightskyblue;
                color: #fff; /* Белый цвет текста */
                padding: 0.5rem 0.7rem; /* Поля вокруг текста */
                text-decoration: none; /* Убираем подчёркивание */
                border-radius: 5px; /* Скругляем уголки */
              }
             </style>
             {% if post.group %}
             <p><a href="{% url 'posts:group_list' post.group.slug %}" class="btn"
             >все записи группы</a>
             {% endif %}
             {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </article>
    </main>

  </body>
{% endblock content %}

yatube/templates/posts/group_list.html
  {% extends 'base.html' %}
    {% block title %}
     Записи сообщества {{ group }}
    {% endblock %}
 {% load thumbnail %}
 {% block content %}
    <main>
      <h1>Записи сообщества</h1>
        <h1> {{ group }} </h1>
        <p>{{ group.description }}</p>
      {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>{{ post.text }}</p>
             <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a></p>
             <style>
               .btn {
                display: inline-block; /* Строчно-блочный элемент */
                background-color: lightskyblue;
                color: #fff; /* Белый цвет текста */
                padding: 0.5rem 0.7rem; /* Поля вокруг текста */
                text-decoration: none; /* Убираем подчёркивание */
                border-radius: 5px; /* Скругляем уголки */
              }
             </style>
             {% if post.group %}
             <p><a href="{% url 'posts:group_list' post.group.slug %}" class="btn"
             >все записи группы</a>
             {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  </main>
 {% endblock %}

yatube/templates/posts/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
{% include 'includes/switcher.html' %}
  <body>

      <h1>Самая главная страница моего амбициозного проекта</h1>
    <main>
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                 <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
             {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
             {% endthumbnail %}
            <p>{{ post.text }}</p>
            <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a></p>
             <style>
               .btn {
                display: inline-block; /* Строчно-блочный элемент */
                background-color: lightskyblue;
                color: #fff; /* Белый цвет текста */
                padding: 0.5rem 0.7rem; /* Поля вокруг текста */
                text-decoration: none; /* Убираем подчёркивание */
                border-radius: 5px; /* Скругляем уголки */
              }
             </style>
             {% if post.group %}
             <p><a href="{% url 'posts:group_list' post.group.slug %}" class="btn"
             >все записи группы</a>
             {% endif %}
             {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </article>
    </main>

  </body>
 {% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

 {% load thumbnail %}
 {% block title %} Пост Первые 100 букв поста {{ post.author.get_full_name }} {% endblock %}
 {% block content %}
      <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group_list' post.group.slug %}"> <br>
                  все записи группы
                </a>
              </li>
            {% endif %}
            <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span > {{ post_count }}</span>
            </li>
            {% if user.is_authenticated %}
              <li class="list-group-item">
                <a href="{% url 'posts:profile' user.username %}">
                  все посты пользователя
                </a>
              </li>
            {% endif %}
          </ul>
        </aside>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
         <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <article class="col-12 col-md-9">
          <p> {{ post.text|truncatechars:100 }} </p>
          {% if user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
          {% endif %}


  {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.pk %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form_comments.text }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}




        </article>
      </div>
    </main>
{% endblock content %}

yatube/templates/posts/profile.html
 {% extends 'base.html' %}
 {% block title %} Записи пользователя {{ user.username }}{% endblock %}
 {% load thumbnail %}
 {% block content %}
    <main>
      <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
            <h3>Всего постов: {{ posts.count }} </h3>
 {% if author != user and user.is_authenticated %}
      {% if following %}
                <a class="btn btn-lg btn-secondary"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
      Отписаться
       </a>
         {% else %}
            <a
            class="btn btn-lg btn-primary"
         href="{% url 'posts:profile_follow' author.username %}" role="button"
             >
       Подписаться
      </a>
   {% endif %}
 </div>
{% endif %}
      <div class="container py-5">
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </div>
    </main>
{% endblock content %}